#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Apr 28 16:15:50 2021

@author: caelus
"""


import numpy as np
import xarray as xr
import matplotlib.pyplot as plt
from tqdm import tqdm
import pandas as pd
import os 

r_path1 = '/home/caelus/dock_1/Working_hub/DATA_dep/Kuroshio/ALL/analysis_sigs/'
r_path2 = '/home/caelus/dock_1/Working_hub/DATA_dep/Kuroshio/'


sig = np.load(r_path1+'first_5.npy')
data = xr.open_dataset(r_path2+'adt_wNpacific_M.nc')
data_a = data - data.mean(dim='time')
tmp_sig = pd.DataFrame({'sig':sig},index = pd.date_range('1993-01-01', periods = 324,freq = 1 * '1m'))

WY = 2
date= pd.date_range('1993-01-01', periods = 324,freq = 1 * '1m')
Rm_sig = tmp_sig.rolling(window=12*WY,center=True).mean()
Rm_data_a = data_a.rolling(time=12*WY,center=True).mean()
Rm_sig.reset_index(inplace=True)
Rm_sig['date'] = pd.date_range('1993-01-01', periods = 324,freq = 1 * '1m').strftime('%Y-%m')
lon,lat = Rm_data_a.lon,Rm_data_a.lat

# =============================================================================
# 
# =============================================================================

from mpl_toolkits.basemap import Basemap
from mpl_toolkits.axes_grid1 import make_axes_locatable


# fig,ax =plt.figure() 
plt.subplot(211)
ax = plt.gca()
m = Basemap(projection='cyl',llcrnrlat=lat[0],urcrnrlat=lat[-1],\
            llcrnrlon=lon[0],urcrnrlon=lon[-1],resolution='i')
# lon2, lat2 = np.meshgrid(lon,lat)
x, y = m(lon, lat)
m.fillcontinents(color='black',lake_color='black')
m.drawcoastlines()
m.drawparallels(np.arange(5.,33.,5.),labels=[True,False,False,False],
                dashes=[2,2],fontsize=18,fontweight='bold',color='grey')
m.drawmeridians(np.arange(-180.,181.,10.),labels=[False,False,False,True],
                dashes=[2,2],fontsize=18,fontweight='bold',color='grey')
plt.title(' jklj ', fontproperties='', position=(0.5, 1.0+0.07), fontsize=34,fontweight='bold')
# plt.suptitle(' UV & speed ',fontstyle='italic',position=(0.5, .92),fontsize=20)
# CS = m.contour(x,y,Corr_map,6,colors='grey')
# ax.clabel(CS,inline=True, fontsize=12,colors='k',fmt='%0.1f')
# CS.collections[6].set_linestyle('dashed')
# CS.collections[6].set_linewidths(3)
# CS.collections[6].set_color('k')

cs = m.pcolormesh(x,y,Rm_data_a.isel(time=13).adt.values,cmap=plt.cm.get_cmap('seismic'),shading='gouraud')
# plt.clim(-1,1)
divider = make_axes_locatable(ax)
cax = divider.append_axes("right", size="2.5%", pad=0.1)
cax.tick_params(labelsize=15)
cax.set_ylabel('m',{'fontsize':20,'fontweight':'bold','style':'italic'})
#label 

h = plt.colorbar(label='',cax=cax);
# plt.savefig('F:/psi36/DATA/temp_var3/meanflow',bbox_inches='tight')

plt.show()



# =============================================================================
# 
# =============================================================================

'''
S = Rm_sig.sig- Rm_sig.sig.mean()


if S[i] >= 0:
    COLOR = 'r'
else:
    COLOR = 'b' 
'''
plt.subplot(212)
ax = plt.gca()
# plt.title('Yan Sun imf05',position=(0.5, 1.0+0.1),
#           fontweight='bold',fontsize='48')

# plt.plot(date,Sig_set_set.stats_model.values,label='statsmodels',color='darkgreen',linewidth=2.5)
# Draw Plot
plt.plot(Rm_sig.date,S, label='SSH Diff (2Y Runing mean)',color='k',linewidth=2.5,zorder=10)

plt.axvline(x=256,linewidth=5,color='k',linestyle='--')
# plt.axhline(y=0,linewidth=2,color='k',linestyle='--')
# plt.axhspan(-.5, .5, facecolor='0.5', alpha=0.2)
# Decoration
# plt.ylim(50,750)

xtick_location = Rm_sig.index.tolist()[::12*2]
xtick_labels = Rm_sig.date.tolist()[::12*2]
plt.xticks(ticks=xtick_location, labels=xtick_labels, rotation=30, fontsize=18, alpha=.7)
# plt.title("Peak and Troughs of Air Passengers Traffic (1949 - 1969)", fontsize=22)
plt.yticks(fontsize=18, alpha=.7)
# Lighten borders
ax.tick_params(labelcolor='k', width=3)

plt.gca().spines["top"].set_alpha(.0)
plt.gca().spines["bottom"].set_alpha(.3)
plt.gca().spines["right"].set_alpha(.0)
plt.gca().spines["left"].set_alpha(.3)
plt.legend(loc='lower left',fontsize=18)
plt.grid(axis='y', alpha=.3)
plt.show()







